# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vynild/review/models/album.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vynild/review/models/album.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n vynild/review/models/album.proto\x12\x14vynild.review.models\"\xa7\x01\n\x0b\x43reateAlbum\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n\x06\x61rtist\x18\x02 \x01(\tR\x06\x61rtist\x12\x14\n\x05genre\x18\x03 \x01(\tR\x05genre\x12!\n\x0crelease_year\x18\x04 \x01(\x05R\x0breleaseYear\x12\x14\n\x05label\x18\x05 \x01(\tR\x05label\x12\x1b\n\talbum_art\x18\x06 \x01(\tR\x08\x61lbumArt\"\xb5\x01\n\tAlbumData\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n\x06\x61rtist\x18\x03 \x01(\tR\x06\x61rtist\x12\x14\n\x05genre\x18\x04 \x01(\tR\x05genre\x12!\n\x0crelease_year\x18\x05 \x01(\x05R\x0breleaseYear\x12\x14\n\x05label\x18\x06 \x01(\tR\x05label\x12\x1b\n\talbum_art\x18\x07 \x01(\tR\x08\x61lbumArtB\x98\x01\n\x18\x63om.vynild.review.modelsB\nAlbumProtoP\x01\xa2\x02\x03VRM\xaa\x02\x14Vynild.Review.Models\xca\x02\x14Vynild\\Review\\Models\xe2\x02 Vynild\\Review\\Models\\GPBMetadata\xea\x02\x16Vynild::Review::Modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vynild.review.models.album_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.vynild.review.modelsB\nAlbumProtoP\001\242\002\003VRM\252\002\024Vynild.Review.Models\312\002\024Vynild\\Review\\Models\342\002 Vynild\\Review\\Models\\GPBMetadata\352\002\026Vynild::Review::Models'
  _globals['_CREATEALBUM']._serialized_start=59
  _globals['_CREATEALBUM']._serialized_end=226
  _globals['_ALBUMDATA']._serialized_start=229
  _globals['_ALBUMDATA']._serialized_end=410
# @@protoc_insertion_point(module_scope)
