# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vynild/review/models/review.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vynild/review/models/review.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vynild.review.models import user_pb2 as vynild_dot_review_dot_models_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!vynild/review/models/review.proto\x12\x14vynild.review.models\x1a\x1fvynild/review/models/user.proto\"\x85\x01\n\x06Review\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x32\n\x04user\x18\x02 \x01(\x0b\x32\x1e.vynild.review.models.UserDataR\x04user\x12\x16\n\x06rating\x18\x03 \x01(\x01R\x06rating\x12\x1f\n\x0breview_text\x18\x04 \x01(\tR\nreviewTextB\x99\x01\n\x18\x63om.vynild.review.modelsB\x0bReviewProtoP\x01\xa2\x02\x03VRM\xaa\x02\x14Vynild.Review.Models\xca\x02\x14Vynild\\Review\\Models\xe2\x02 Vynild\\Review\\Models\\GPBMetadata\xea\x02\x16Vynild::Review::Modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vynild.review.models.review_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.vynild.review.modelsB\013ReviewProtoP\001\242\002\003VRM\252\002\024Vynild.Review.Models\312\002\024Vynild\\Review\\Models\342\002 Vynild\\Review\\Models\\GPBMetadata\352\002\026Vynild::Review::Models'
  _globals['_REVIEW']._serialized_start=93
  _globals['_REVIEW']._serialized_end=226
# @@protoc_insertion_point(module_scope)
