# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vynild/review/models/user.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vynild/review/models/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fvynild/review/models/user.proto\x12\x14vynild.review.models\"L\n\x08UserData\x12\x0e\n\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mailB\x97\x01\n\x18\x63om.vynild.review.modelsB\tUserProtoP\x01\xa2\x02\x03VRM\xaa\x02\x14Vynild.Review.Models\xca\x02\x14Vynild\\Review\\Models\xe2\x02 Vynild\\Review\\Models\\GPBMetadata\xea\x02\x16Vynild::Review::Modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vynild.review.models.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.vynild.review.modelsB\tUserProtoP\001\242\002\003VRM\252\002\024Vynild.Review.Models\312\002\024Vynild\\Review\\Models\342\002 Vynild\\Review\\Models\\GPBMetadata\352\002\026Vynild::Review::Models'
  _globals['_USERDATA']._serialized_start=57
  _globals['_USERDATA']._serialized_end=133
# @@protoc_insertion_point(module_scope)
