volumes:
  mongo_data: {}
  redis_data: {}

services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    restart: unless-stopped
