# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vynild/review/services/album_service.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vynild/review/services/album_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vynild.review.models import album_pb2 as vynild_dot_review_dot_models_dot_album__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*vynild/review/services/album_service.proto\x12\x16vynild.review.services\x1a vynild/review/models/album.proto\",\n\x0fGetAlbumRequest\x12\x19\n\x08\x61lbum_id\x18\x01 \x01(\tR\x07\x61lbumId\"I\n\x10GetAlbumResponse\x12\x35\n\x05\x61lbum\x18\x01 \x01(\x0b\x32\x1f.vynild.review.models.AlbumDataR\x05\x61lbum\"/\n\x10GetAlbumsRequest\x12\x1b\n\tartist_id\x18\x01 \x01(\tR\x08\x61rtistId\"L\n\x11GetAlbumsResponse\x12\x37\n\x06\x61lbums\x18\x01 \x03(\x0b\x32\x1f.vynild.review.models.AlbumDataR\x06\x61lbums2\xcf\x01\n\x0c\x41lbumService\x12]\n\x08GetAlbum\x12\'.vynild.review.services.GetAlbumRequest\x1a(.vynild.review.services.GetAlbumResponse\x12`\n\tGetAlbums\x12(.vynild.review.services.GetAlbumsRequest\x1a).vynild.review.services.GetAlbumsResponseB\xa9\x01\n\x1a\x63om.vynild.review.servicesB\x11\x41lbumServiceProtoP\x01\xa2\x02\x03VRS\xaa\x02\x16Vynild.Review.Services\xca\x02\x16Vynild\\Review\\Services\xe2\x02\"Vynild\\Review\\Services\\GPBMetadata\xea\x02\x18Vynild::Review::Servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vynild.review.services.album_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.vynild.review.servicesB\021AlbumServiceProtoP\001\242\002\003VRS\252\002\026Vynild.Review.Services\312\002\026Vynild\\Review\\Services\342\002\"Vynild\\Review\\Services\\GPBMetadata\352\002\030Vynild::Review::Services'
  _globals['_GETALBUMREQUEST']._serialized_start=104
  _globals['_GETALBUMREQUEST']._serialized_end=148
  _globals['_GETALBUMRESPONSE']._serialized_start=150
  _globals['_GETALBUMRESPONSE']._serialized_end=223
  _globals['_GETALBUMSREQUEST']._serialized_start=225
  _globals['_GETALBUMSREQUEST']._serialized_end=272
  _globals['_GETALBUMSRESPONSE']._serialized_start=274
  _globals['_GETALBUMSRESPONSE']._serialized_end=350
  _globals['_ALBUMSERVICE']._serialized_start=353
  _globals['_ALBUMSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
