# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vynild/review/services/review_service.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vynild/review/services/review_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vynild.review.models import review_pb2 as vynild_dot_review_dot_models_dot_review__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+vynild/review/services/review_service.proto\x12\x16vynild.review.services\x1a!vynild/review/models/review.proto\"/\n\x10GetReviewRequest\x12\x1b\n\treview_id\x18\x01 \x01(\tR\x08reviewId\"I\n\x11GetReviewResponse\x12\x34\n\x06review\x18\x01 \x01(\x0b\x32\x1c.vynild.review.models.ReviewR\x06review\".\n\x11GetReviewsRequest\x12\x19\n\x08\x61lbum_id\x18\x01 \x01(\tR\x07\x61lbumId\"L\n\x12GetReviewsResponse\x12\x36\n\x07reviews\x18\x01 \x03(\x0b\x32\x1c.vynild.review.models.ReviewR\x07reviews\"\x82\x01\n\x13\x43reateReviewRequest\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\x12\x16\n\x06rating\x18\x02 \x01(\x01R\x06rating\x12\x1f\n\x0breview_text\x18\x03 \x01(\tR\nreviewText\x12\x19\n\x08\x61lbum_id\x18\x04 \x01(\tR\x07\x61lbumId\"3\n\x14\x43reateReviewResponse\x12\x1b\n\treview_id\x18\x01 \x01(\tR\x08reviewId2\xc1\x02\n\rReviewService\x12`\n\tGetReview\x12(.vynild.review.services.GetReviewRequest\x1a).vynild.review.services.GetReviewResponse\x12\x63\n\nGetReviews\x12).vynild.review.services.GetReviewsRequest\x1a*.vynild.review.services.GetReviewsResponse\x12i\n\x0c\x43reateReview\x12+.vynild.review.services.CreateReviewRequest\x1a,.vynild.review.services.CreateReviewResponseB\xaa\x01\n\x1a\x63om.vynild.review.servicesB\x12ReviewServiceProtoP\x01\xa2\x02\x03VRS\xaa\x02\x16Vynild.Review.Services\xca\x02\x16Vynild\\Review\\Services\xe2\x02\"Vynild\\Review\\Services\\GPBMetadata\xea\x02\x18Vynild::Review::Servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vynild.review.services.review_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.vynild.review.servicesB\022ReviewServiceProtoP\001\242\002\003VRS\252\002\026Vynild.Review.Services\312\002\026Vynild\\Review\\Services\342\002\"Vynild\\Review\\Services\\GPBMetadata\352\002\030Vynild::Review::Services'
  _globals['_GETREVIEWREQUEST']._serialized_start=106
  _globals['_GETREVIEWREQUEST']._serialized_end=153
  _globals['_GETREVIEWRESPONSE']._serialized_start=155
  _globals['_GETREVIEWRESPONSE']._serialized_end=228
  _globals['_GETREVIEWSREQUEST']._serialized_start=230
  _globals['_GETREVIEWSREQUEST']._serialized_end=276
  _globals['_GETREVIEWSRESPONSE']._serialized_start=278
  _globals['_GETREVIEWSRESPONSE']._serialized_end=354
  _globals['_CREATEREVIEWREQUEST']._serialized_start=357
  _globals['_CREATEREVIEWREQUEST']._serialized_end=487
  _globals['_CREATEREVIEWRESPONSE']._serialized_start=489
  _globals['_CREATEREVIEWRESPONSE']._serialized_end=540
  _globals['_REVIEWSERVICE']._serialized_start=543
  _globals['_REVIEWSERVICE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
