# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vynild/forum/models/room.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vynild/forum/models/room.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1evynild/forum/models/room.proto\x12\x13vynild.forum.models\"P\n\nCreateRoom\x12\x1b\n\x08\x61lbum_id\x18\x01 \x01(\tH\x00R\x07\x61lbumId\x12\x16\n\x05genre\x18\x02 \x01(\tH\x00R\x05genreB\r\n\x0broom_target\"^\n\x08RoomData\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\x08\x61lbum_id\x18\x02 \x01(\tH\x00R\x07\x61lbumId\x12\x16\n\x05genre\x18\x03 \x01(\tH\x00R\x05genreB\r\n\x0broom_targetB\x92\x01\n\x17\x63om.vynild.forum.modelsB\tRoomProtoP\x01\xa2\x02\x03VFM\xaa\x02\x13Vynild.Forum.Models\xca\x02\x13Vynild\\Forum\\Models\xe2\x02\x1fVynild\\Forum\\Models\\GPBMetadata\xea\x02\x15Vynild::Forum::Modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vynild.forum.models.room_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.vynild.forum.modelsB\tRoomProtoP\001\242\002\003VFM\252\002\023Vynild.Forum.Models\312\002\023Vynild\\Forum\\Models\342\002\037Vynild\\Forum\\Models\\GPBMetadata\352\002\025Vynild::Forum::Models'
  _globals['_CREATEROOM']._serialized_start=55
  _globals['_CREATEROOM']._serialized_end=135
  _globals['_ROOMDATA']._serialized_start=137
  _globals['_ROOMDATA']._serialized_end=231
# @@protoc_insertion_point(module_scope)
